name = "app-name"
compatibility_date = "2024-08-06"
compatibility_flags = [ "nodejs_compat" ]
main = "src/server/index.ts"

[dev]
port = 8080
[vars]
DATABASE_URL = "postgresql://neondb_owner:npg_5b9ZIFeMjSrW@ep-orange-leaf-a8pheixc-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"
BETTER_AUTH_SECRET = "ejCHlmnZb45NiHQwkfDJgknRrHViVI79"
BETTER_AUTH_URL = "http://localhost:3000"
GOOGLE_CLIENT_ID = "656118512904-a9uu8n0flba6gm6aonbbfqi9tegced8m.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
